name: API_CI
# on: ['push']
on:
  push:
    paths:
    - "api/**"
    - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json

      - name: instal dependecies
        run: npm install

      - name: Run tests
        run: npm run test

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json

      - name: instal dependecies
        run: npm install

      - name: Run tests
        run: npm run lint

  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:14
    services:
      mongo-e2e:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test123
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: instal dependecies
        run: npm install

      - name: Run tests e2e
        run: npm run test:e2e
        env:
          MONGO_DB_NAME: demo
          MONGO_URL: mongodb://test:test123@mongo-e2e:27017?retryWrites=true&writeConcern=majority


